### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/lewis-carroll_a-tangled-tale#1]
- Missing copy and paste CSS for epigraphs in section headers

- Text `The final numbers are 1 × ⅕ × 3, ⅖ × ⅔ × 1, ⅔ × 1 × ¼` should be in mathml

-    For mathml, we want "content" mathml versus "presentational" mathml where possible: https://standardebooks.org/manual/1.0.0/8-typography#8.8.6.2.2

      The kind of math in this book is perfect for content mathml; it's mostly unambiguous and pretty basic. I don't think Firefox has built-in support for content mathml, but the build tool does convert it to presentational for the compatible epub. At this point it would be a pain in the butt to convert and debug but it *is* in the manual. What do you think?

**Comment by robinwhittleton** [comment]
Missing CSS fixed in https://github.com/robinwhittleton/lewis-carroll_a-tangled-tale/commit/6d097af3934633730e6c0c05fca1c8a04bf43b2f.

Missing MathML fixed in https://github.com/robinwhittleton/lewis-carroll_a-tangled-tale/commit/eba3aff42972c6762583ab361107eb99a805f5f8.

For Content MathML, I’m possibly missing something, but I don’t think our pipeline is set up to build it correctly. I’ve taken a copy of the first two equations in the appendix and converted them as best I can to Content MathML:

```html
<ol>
	<li>
		<p>“<m:math alttext="y = 6 − ((x − 3y) ÷ 6)"><m:apply><m:eq/><m:ci>y</m:ci><m:apply><m:minus/><m:cn>6</m:cn><m:apply><m:divide/><m:apply><m:minus/><m:ci>x</m:ci><m:apply><m:multiply/><m:cn>3</m:cn><m:ci>y</m:ci></m:apply></m:apply><m:cn>6</m:cn></m:apply></m:apply></m:apply></m:math>;</p>
	</li>
	<li>
		<p><m:math alttext="x ÷ 4½ = 6"><m:apply><m:eq/><m:apply><m:divide/><m:ci>x</m:ci><m:cn>4½</m:cn></m:apply><m:cn>6</m:cn></m:apply></m:math>”</p>
	</li>
</ol>
```

Running this through the build pipeline ends up with this (presentational above, content below):

<img width="152" alt="Screenshot 2020-06-24 at 17 44 30" src="https://user-images.githubusercontent.com/7414/85587960-885b4100-b642-11ea-869f-8748c5a4daba.png">

I tried installing the [Content MathML Polyfill](https://github.com/fred-wang/webextension-content-mathml-polyfill) into Firefox to test there, and I get this:

<img width="175" alt="Screenshot 2020-06-24 at 17 46 53" src="https://user-images.githubusercontent.com/7414/85588150-b80a4900-b642-11ea-8b1d-610de7eef382.png">

So mildly better, but still not exactly great compared to the original rendering. So what do you think? Shall I try to patch the XSL from the polyfill into the build chain?

**Comment by robinwhittleton** [comment]
Oh yeah, and I scanned the corpus for other Content MathML elements and couldn’t find any…

**Comment by acabal** [comment]
There's no content mathml in the corpus because IIRC _Tractatus_ is the only book with serious mathml, and he wrote it using a non-standard notation that is not unambiguous (scholars are still arguing about it today). If you build for kobo it looks like the XSL conversion isn't happening at all; the file still has content mathml after processing. Not sure why. I'll have to take a closer look later today. Let's put this aside for now.

**Comment by robinwhittleton** [comment]
OK! I’m more than happy to help with any testing, etc.

**Comment by acabal** [comment]
OK, turns out is was a simple regex problem. But, the output still isn't great, definitely not up to the same appearance as the presentational. So, let's leave it.
